apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: job
    app.kubernetes.io/name: lms-job-20221129184220
  name: lms-job-20221129184220
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - args:
        - sh
        - -e
        - -c
        - '(./manage.py lms waffle_flag --list | grep account.redirect_to_microfrontend)
          || ./manage.py lms waffle_flag --create --everyone account.redirect_to_microfrontend




          (./manage.py lms waffle_flag --list | grep learner_profile.redirect_to_microfrontend)
          || ./manage.py lms waffle_flag --create --everyone learner_profile.redirect_to_microfrontend

          site-configuration set --domain=openedx.untic-fibog.com ENABLE_PROFILE_MICROFRONTEND
          true

          site-configuration set --domain=openedx.untic-fibog.com:8000 ENABLE_PROFILE_MICROFRONTEND
          true




          (./manage.py lms waffle_flag --list | grep course_home.course_home_mfe_progress_tab)
          || ./manage.py lms waffle_flag --create --everyone course_home.course_home_mfe_progress_tab'
        env:
        - name: SERVICE_VARIANT
          value: lms
        - name: DJANGO_SETTINGS_MODULE
          value: lms.envs.tutor.production
        image: docker.io/dbayonac/openedx:latest
        name: lms
        volumeMounts:
        - mountPath: /openedx/edx-platform/lms/envs/tutor/
          name: settings-lms
        - mountPath: /openedx/edx-platform/cms/envs/tutor/
          name: settings-cms
        - mountPath: /openedx/config
          name: config
      restartPolicy: Never
      volumes:
      - configMap:
          name: openedx-settings-lms
        name: settings-lms
      - configMap:
          name: openedx-settings-cms
        name: settings-cms
      - configMap:
          name: openedx-config
        name: config
  ttlSecondsAfterFinished: 3600
