apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: job
    app.kubernetes.io/name: lms-job-20221122171800
  name: lms-job-20221122171800
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - args:
        - sh
        - -e
        - -c
        - '

          echo "Loading settings $DJANGO_SETTINGS_MODULE"


          ./manage.py lms manage_user  --superuser --staff vdiegox dbayonac@unal.edu.co


          ./manage.py lms shell -c "from django.contrib.auth import get_user_model

          u = get_user_model().objects.get(username=''vdiegox'')

          u.set_password(''superadmin'')

          u.save()"

          '
        env:
        - name: SERVICE_VARIANT
          value: lms
        - name: DJANGO_SETTINGS_MODULE
          value: lms.envs.tutor.production
        image: docker.io/dbayonac/openedx:latest
        name: lms
        volumeMounts:
        - mountPath: /openedx/edx-platform/lms/envs/tutor/
          name: settings-lms
        - mountPath: /openedx/edx-platform/cms/envs/tutor/
          name: settings-cms
        - mountPath: /openedx/config
          name: config
      restartPolicy: Never
      volumes:
      - configMap:
          name: openedx-settings-lms
        name: settings-lms
      - configMap:
          name: openedx-settings-cms
        name: settings-cms
      - configMap:
          name: openedx-config
        name: config
  ttlSecondsAfterFinished: 3600
