CMS_HOST: studio.openedx.untic-fibog.com
CMS_OAUTH2_SECRET: o1jbau4lLSbpaxva6ud84ujV
CONTACT_EMAIL: dbayonac@unal.edu.co
DOCKER_IMAGE_OPENEDX: docker.io/dbayonac/openedx:latest
ENABLE_HTTPS: true
ENABLE_WEB_PROXY: false
ID: LVj27qM9Je4MNFJiKBzdxlP8
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAr5WmoCngKEcbQnOwONMYjaI788M+I1V7O/tNtOsJ0IrX3J4P

  7qkMdr302WotD1q4KniU3ns5iY+UJSJx8sOl7Qp6JqTlFFAiBZ7r7mbDUtJylLUT

  yPTk5OE2bDxGjyybFjsLw3aEEwaSgWojVLfmSp0kTJZGLNMKqh6arG0dswbPqV2h

  ke/b5Yz1g8oe/t6CPxIxCN/Bczi+3K8baRm4wXWKoD51fbLdJKECYKYRzHmtXF61

  DWw/ywVrZiUomNx5cQudwrCZhZGqouMPEareXkk89Ux3hCOZ3Hfn/OhlNh2aWQMe

  XVr2MudC8C+TkmSBOq4B5gIjA6wRJx4vYKiqUwIDAQABAoIBAEsgu7J1KHnjbukA

  iirOPAfCHmffJvPEbB3OmcGq/cCS3+kAYq3J/FDEV4M9eHlE5l8ZyAzn6ccPvaIj

  +mCW0SS7Imftjy0hWmVQSf/wTWvfKvKxBf2qt1Otf3VRVxmEyvj4m8BvMfTYD5C7

  ItHpe+p6EWGJvQ4J4NrIjILxj08dicxQRxDDKP7/C1IW+UqaRYPY2sEq5SBWK8uG

  Ou0awXD2UO29oWj43jb2mLs2UNHfdNQgYKCD4tH/t/poGEtNV08GbtlHMA8IJi86

  noYafC/U2f5dkcny6l6jGRjghyDYAnT4T14aQPRNDLHk8kPyHTMbaarcROcdRpeJ

  kffZfl0CgYEAyZSg/8dlazC6v+xgwtEEY+4j5eOyqLqh0cUsYdhu+vJGRRxAoBV+

  1Tp0FawsXhu4GR9SNluuRyMye3Nue6Qvl1rz5CaN4rGxRwe7qa/mp8hEPog6WIir

  3PUcztFugYFNewKrsFsrGM/YLYXqo/V+WUlJmurrbjpbjuARvFL+ko0CgYEA3vxr

  kbpOiSvnWGxVB7fsYpfhbexV6mkSBld+SK2M7LWQvxFGxWAAqJL80gfk6XAJLbOh

  3wX7ma8p4XHs7eqavNOATE10RJcjIIZfbfT1YGZmjSpoaiFTPr2TZruZg28lVTIn

  riW9ckkniDLaXQPhAqSfZxCnGjNYbTxz23UDaF8CgYAUd3C5R4d2kKYFYnyYixxF

  ASLH7oxvMTPI1pog/RaXiA22ap3tIwGTqLGsmaSPkYTpmBKCzmAtfNddTWUETLFA

  Ts3AdmGliKEVMyXMnr1uf5jeOHqkDoxUjNZ18TGlGHnDaYwBBeCkTkYGqTgfmYdQ

  jW5ZukxZDrfJE9r5IfwS6QKBgBmBNayNar41z1hFy9P+LYN5a8du6MTPD8i56S/W

  6e+JNO0lxLp+qJSfe1tqm7w3nFUl3rXrsUN6zYeDyF3OH7TJXDteAJZ30wS9Wdzx

  z78e90veNeMtvJ/IfzuY6Y4nAFYmTnOUzX5s76CccG2DLBFpUvIu7W4JwWt9JqNL

  VwBxAoGAe3Lo/PTuD6Ig9GXZXkThoEs3XDO5a3poSw4sdZ7DfgDxS1S/dGeu9T/u

  5l+XUUCQlwfHM7dZOVu5Dtx1Z/GPOLAFuqOHgkX3mwP2vhze0vvf1IstZu/rgEcj

  gSdcOOUWy8lRSOLxDNlg9BP+ejkAEHfYmabSTItatY6y6EDePjM=

  -----END RSA PRIVATE KEY-----'
K8S_NAMESPACE: open-edx
LANGUAGE_CODE: en
LMS_HOST: openedx.untic-fibog.com
MFE_DOCKER_IMAGE: docker.io/dbayonac/openedx-mfe:latest
MINIO_AWS_SECRET_ACCESS_KEY: 3A1IjjZamwI7sHQ3SxZ1qkrZ
MYSQL_ROOT_PASSWORD: MPaPSS0u
OPENEDX_AWS_ACCESS_KEY: openedx
OPENEDX_AWS_SECRET_ACCESS_KEY: 3A1IjjZamwI7sHQ3SxZ1qkrZ
OPENEDX_MYSQL_PASSWORD: L06M56xQ
OPENEDX_SECRET_KEY: KQWwu7sMbuBsqPNbytm3f59p
PLATFORM_NAME: UNEdx
PLUGINS:
- jupyter_viewer
- mfe
- minio
