version: "3.7"
services:

    mysql-job:
      image: docker.io/mysql:5.7.35
      depends_on: ["mysql"]

    lms-job:
      image: docker.io/dbayonac/openedx:latest
      environment:
        SERVICE_VARIANT: lms
        DJANGO_SETTINGS_MODULE: lms.envs.tutor.production
      volumes:
        - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
        - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
        - ../apps/openedx/config:/openedx/config:ro
      depends_on: ["mysql", "mongodb"]

    cms-job:
      image: docker.io/dbayonac/openedx:latest
      environment:
        SERVICE_VARIANT: cms
        DJANGO_SETTINGS_MODULE: cms.envs.tutor.production
      volumes:
        - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
        - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
        - ../apps/openedx/config:/openedx/config:ro
      depends_on: ["mysql", "mongodb", "elasticsearch", "redis"]

    # MinIO
    minio-job:
      image: docker.io/minio/mc:RELEASE.2022-05-09T04-08-26Z
      environment:
        MINIO_ROOT_USER: "openedx"
        MINIO_ROOT_PASSWORD: "3A1IjjZamwI7sHQ3SxZ1qkrZ"
      entrypoint: []
      depends_on: ["minio"]