SITE_NAME: "untic-fibog.com"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "http://untic-fibog.com/oauth2"
PLATFORM_NAME: "UNEdx"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.untic-fibog.com"
  ENABLE_CORS_HEADERS: true
  ENABLE_COURSE_DISCOVERY: true
  ENABLE_COURSEWARE_SEARCH: true
  ENABLE_CSMH_EXTENDED: false
  ENABLE_DASHBOARD_SEARCH:  true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_LEARNER_RECORDS: false
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PREREQUISITE_COURSES: true
  ENABLE_THIRD_PARTY_AUTH: true
  MILESTONES_APP: true
  PERSISTENT_GRADES_ENABLED_FOR_ALL_TESTS: true
LMS_ROOT_URL: "http://untic-fibog.com"
CMS_ROOT_URL: "http://studio.untic-fibog.com"
CMS_BASE: "studio.untic-fibog.com"
LMS_BASE: "untic-fibog.com"
CONTACT_EMAIL: "dbayonac@unal.edu.co"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "cms"
ENABLE_COMPREHENSIVE_THEMING: true
COMPREHENSIVE_THEME_DIRS: ["/openedx/themes"]
STATIC_ROOT_BASE: "/openedx/staticfiles"
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "smtp"
EMAIL_PORT: 8025
EMAIL_USE_TLS: false
ACE_ROUTING_KEY: "edx.lms.core.default"
HTTPS: "off"
LANGUAGE_CODE: "en"
SESSION_COOKIE_DOMAIN: "untic-fibog.com"

CACHES:
  default:
    KEY_PREFIX: "default"
    VERSION: "1"
    BACKEND: "django_redis.cache.RedisCache"
    LOCATION: "redis://@redis:6379/1"
  general:
    KEY_PREFIX: "general"
    BACKEND: "django_redis.cache.RedisCache"
    LOCATION: "redis://@redis:6379/1"
  mongo_metadata_inheritance:
    KEY_PREFIX: "mongo_metadata_inheritance"
    TIMEOUT: 300
    BACKEND: "django_redis.cache.RedisCache"
    LOCATION: "redis://@redis:6379/1"
  staticfiles:
    KEY_PREFIX: "staticfiles_lms"
    BACKEND: "django.core.cache.backends.locmem.LocMemCache"
    LOCATION: "staticfiles_lms"
  configuration:
    KEY_PREFIX: "configuration"
    BACKEND: "django_redis.cache.RedisCache"
    LOCATION: "redis://@redis:6379/1"
  celery:
    KEY_PREFIX: "celery"
    TIMEOUT: "7200"
    BACKEND: "django_redis.cache.RedisCache"
    LOCATION: "redis://@redis:6379/1"
  course_structure_cache:
    KEY_PREFIX: "course_structure"
    TIMEOUT: "7200"
    BACKEND: "django_redis.cache.RedisCache"
    LOCATION: "redis://@redis:6379/1"
  ora2-storage:
    KEY_PREFIX: "ora2-storage"
    BACKEND: "django_redis.cache.RedisCache"
    LOCATION: "redis://@redis:6379/1"
SECRET_KEY: "KQWwu7sMbuBsqPNbytm3f59p"
AWS_ACCESS_KEY_ID: "openedx"
AWS_SECRET_ACCESS_KEY: "3A1IjjZamwI7sHQ3SxZ1qkrZ"
DOC_STORE_CONFIG: null
AWS_STORAGE_BUCKET_NAME: "openedx"
AWS_S3_CUSTOM_DOMAIN: ""
AWS_QUERYSTRING_AUTH: false
XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "L06M56xQ"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
EMAIL_HOST_USER: ""
EMAIL_HOST_PASSWORD: ""